name: Test Clair publish Scan
on: [push]

jobs: Publish Report
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: action/checkout@v2
    - name: Test publish action
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '/assets/clair-result/*.xml'
    - name: Test Publish 2
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: assets/**/*.xml


