name: Test Clair publish Scan
on: [push]

jobs:
  publish-report:
    name: Publis Clair report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: convert2Junit
        run: |
          echo 'Install test requirements'
          pip install --upgrade pip
          pip install -r requirements.txt --upgrade
          python clair_to_junit_parser.py assets/clair-result/clair-report.json --output assets/clair-scanner-results.xml
          cat assets/clair-scanner-results.xml
      - name: List files
        run: |
          ls -lta assets/
      - name: Test publish action
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: assest/**/*.xml


