name: Test Clair publish Scan
on: [push]

jobs:
  publish-report:
    name: Publis Clair report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: convert2Junit
        run: |
          python clair_to_junit_parser.py assets/clair-result/clainr-report.json --output assest/clair-scanner-results.xml
          cat assest/clair-scanner-results.xml
      - name: Test publish action
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: assest/clair-scanner-results.xml


