name: Test Clair publish Scan
on: [push]

jobs:
  publish-report:
    name: Publis Clair report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test publish action
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: assets/**/*.json
      - name: Test Publish 2
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          if: always()
          files: assets/**/*.json


